export const INCANTATIONS: Record<string, string> = {
	"ex codice lumen": "from code, light",
};

export const NORMALIZED_ALIASES: Record<string, string> = {
	"-h": "help",
	"--help": "help",
	"ls /": "ls",
	"ls work": "ls /work",
	"ls stack": "ls /stack",
	"open hire": "open /hire",
	quit: "exit",
	"rm -rf /": "rm -rf .",
	"rm -rf ~": "rm -rf .",
	vi: "vim",
	nano: "vim",
	emacs: "vim",
	hyrule: "zelda",
	"outie mode": "outie",
	"rpg mode": "mode rpg",
};

export const RPG_MODE_LINES = [
	"",
	"  *  .  *  .  *  .  *  .  *  .  *",
	"",
	"  __     /\\  /\\  /\\     __",
	" /o \\~  /  \\/  \\/  \\  ~/o \\",
	"/____\\ |____________| /____\\",
	"  ||                    ||",
	"",
	"    ____  ____   ____ ",
	"   |  _ \\|  _ \\ / ___|",
	"   | |_) | |_) || |  _",
	"   |  _ <|  __/ | |_| |",
	"   |_| \\_\\|_|   \\____|",
	"",
	"            M O D E",
	"",
	"  *  .  *  .  *  .  *  .  *  .  *",
	"",
	"  the spirits of the console stir...",
];

export const topLevelCommands = [
	"whoami",
	"help",
	"-h",
	"ls",
	"cat",
	"contact",
	"open",
	"echo",
	"git",
	"sudo",
	"clear",
	"exit",
	"quit",
	"rm",
	"vim",
	"vi",
	"nano",
	"emacs",
	"mode",
	"chocobo",
	"ritual",
	"summon",
	"translate",
	"innie",
	"outie",
	"macrodata",
	"waffleparty",
	"severed",
];

export function getArgMap(): Record<string, string[]> {
	return {
		ls: ["work", "/work", "stack", "/stack"],
		cat: ["resume.txt"],
		open: ["hire", "/hire"],
		git: ["log"],
		mode: ["rpg", "terminal"],
		sudo: ["hire adam"],
		ritual: [],
		summon: [],
		translate: Object.keys(INCANTATIONS),
		innie: [],
		outie: [],
		macrodata: [],
		waffleparty: [],
		severed: [],
	};
}
